// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SaveWorldProject.Models;
using System;

namespace SaveWorldProject.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20201016113122_UpdateTable")]
    partial class UpdateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaveWorldProject.Models.columnChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Poluant");

                    b.Property<string>("Source");

                    b.Property<int>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("columnCharts");
                });

            modelBuilder.Entity("SaveWorldProject.Models.continentsMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Continent");

                    b.Property<float>("Valoare");

                    b.Property<string>("cod3");

                    b.HasKey("Id");

                    b.ToTable("continents");
                });

            modelBuilder.Entity("SaveWorldProject.Models.Emission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<string>("Denumire");

                    b.Property<float>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("emissions");
                });

            modelBuilder.Entity("SaveWorldProject.Models.EmissionByContinent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<string>("Continent");

                    b.Property<float>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("continentsData");
                });

            modelBuilder.Entity("SaveWorldProject.Models.emissionChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<string>("MemberStates");

                    b.Property<float>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("emissionsChart");
                });

            modelBuilder.Entity("SaveWorldProject.Models.EmissionsBySource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Poluant");

                    b.Property<string>("Source");

                    b.Property<int>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("emissionsBySources");
                });

            modelBuilder.Entity("SaveWorldProject.Models.ForestMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<float>("Valoare");

                    b.Property<string>("cod3");

                    b.HasKey("Id");

                    b.ToTable("forestMaps");
                });

            modelBuilder.Entity("SaveWorldProject.Models.IncalzireaGlobala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<float>("Valoare");

                    b.HasKey("Id");

                    b.ToTable("incalzireaGlobala");
                });

            modelBuilder.Entity("SaveWorldProject.Models.MapChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<float>("Valoare");

                    b.Property<string>("cod3");

                    b.HasKey("Id");

                    b.ToTable("MapsChart");
                });

            modelBuilder.Entity("SaveWorldProject.Models.PollutionMap2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Valoare");

                    b.Property<string>("cod3");

                    b.HasKey("Id");

                    b.ToTable("pollutionMap2s");
                });

            modelBuilder.Entity("SaveWorldProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa");

                    b.Property<string>("Email");

                    b.Property<string>("Nume");

                    b.Property<int>("Varsta");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
